runmode: debug # debug, release, test
port: :8081
name: blog
url: listen_url_example
database:
  name: blog
  url: db_url_example
  username: root
  password: db_password_example
  params: charset=utf8&parseTime=True&loc=Asia/Shanghai
mysqllog: true
jwt_secret: jwt_secret_example
# 阿里云
uploadUrl: http://gilgamesh.oss-cn-hongkong.aliyuncs.com
endPoint: oss-cn-hongkong.aliyuncs.com
accessKeyId: accessKeyId_example
accessKeySecret: accessKeySecret_example
bucketName: gilgamesh